name: beer_run
version: 0.0.0
author: Kyle Racette <kracette@gmail.com>
description: A top down arcade game
dependencies:
  browser: any
  intl: any
  logging: '>=0.9.1+1 <0.10.0'
  quiver: '>=0.18.0<0.19.0'
dev_dependencies:
  unittest: any
